### ISSUE TITLE
Add pr-size-labeler for Github Action

### ISSUE THREAD

**Issue by nmarulo** [despensa-app/despensa-html#2]
> [!IMPORTANT]
> Read issue #1 first

I've seen how this Github Action works and would like to add it to my repository. If anyone wants to try to add it, go ahead.

This is the repository with the documentation: https://github.com/CodelyTV/pr-size-labeler

Thank you very much.

**Comment by prxjwal** [comment]
would like to implement could u assign me this

**Comment by nmarulo** [comment]
@prxjwal It's all yours 👍
