### ISSUE TITLE
Alternative to modal window

### ISSUE THREAD

**Issue by nmarulo** [despensa-app/despensa-html#3]
> [!IMPORTANT]
> Read issue #1 first

I attach some videos to give a graphic idea of what I want to try to do.

It doesn't have to be exactly the same, but something close.

The vertical displacement with the click is optional.

https://github.com/user-attachments/assets/f58ae956-2370-40d4-b23f-af717e000707

https://github.com/user-attachments/assets/d47292a0-dd70-4c1e-8a3b-3ef2d666d59c

**Comment by Swayam-hue** [comment]
Assign me this issue.

**Comment by Swayam-hue** [comment]
PR sent already. Please check.

**Comment by nmarulo** [comment]
As stated in issue #1

> Each issue noted with hacktoberfest must be completed within a week and you can only do one per week, this is to give more participants a chance. ...

It's okay that you were not able to complete it, I appreciate your effort and interest.
